bot:
  automerge: true
build_platform:
  osx_arm64: osx_64
conda_build_tool: rattler-build
conda_forge_output_validation: true
# `conda_install_tool: pixi` is incompatible with `ppc64le`: https://github.com/conda-forge/conda-smithy/issues/2350
# conda_install_tool: pixi
provider:
  linux_aarch64: default
  linux_ppc64le: default
